AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5 # lowest supported version
  Exclude:
    - vendor/**/*
    - gemfiles/vendor/**/*

LineLength:
  Max: 120

ClassLength:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

HashSyntax:
   EnforcedStyle: ruby19

Style/SignalException:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/IndentFirstArgument:
  Enabled: false

Layout/IndentFirstHashElement:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
